import type { Metadata } from "next";

import { auth } from "@/auth";
import TopNav from "@/components/navbar/TopNav";
import Providers from "@/components/Providers";

import "./globals.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const session = await auth();
	const userId = session?.user?.id || null;

	return (
		<html lang="en">
			<body>
				<TopNav />
				<main className="container mx-auto">
					<Providers userId={userId}>{children}</Providers>
				</main>
			</body>
		</html>
	);
}
